default-ks.cfg: install python3-lxml instead of python-lxml
python-lxml doesn't exist in RHEL8 repo. Try to use python2-lxml.
But can't fix issue. Using python3-lxml fix this error "Python
ImportError: No module named 'lxml'".

Signed-off-by: xiaoli feng <xifeng@redhat.com>